#nacos:
#  server-addr: 192.168.3.2:8848
#  user-name: base
#  password: base
#  namespace: base
web-server:
  port: 8080
  context-path: /base
logger:
  level: 5
  filename: base.log
  max-size: 50
  max-age: 10
  max-backups: 20
  compress: true
mysql:
  host: 192.168.3.2
  port: 3306
  user-name: root
  password: root
  db-name: base
  max-idle: 10
  max-conn: 20
  max-life: 120
redis:
  server-address: localhost:6379
  password: 123456
  db: 1
  pool-size: 2
  min-idle-cones: 1